---
__packages:
  - composer
  - php7.0-bz2
  - php7.0-cli
  - php7.0-curl
  - php7.0-fpm
  - php7.0-gd
  - php7.0-intl
  - php7.0-json
  - php7.0-mbstring
  - php7.0-mysql
  - php7.0-opcache
  - php7.0-readline
  - php7.0-soap
  - php7.0-xml
  - php7.0-zip
  - php-redis
