- name: Include global variables
  include_vars: variables/main.yml

- name: Update apt cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ __clamav_packages }}"

- name: Start clamav-freshclam
  become: true
  service:
    name: clamav-freshclam
    state: started

- name: Start clamav-daemon
  become: true
  service:
    name: clamav-daemon
    state: started

- name: Create quarantine dir
  become: true
  file:
    path: "{{ quarantine }}"
    state: directory
    mode: 0666
  when: cron_tabs

- name: Add cron jobs
  become: true
  cron:
    name: "virus scan {{ item.dir }}"
    job: "clamscan -r --infected --move={{ quarantine }} --exclude={{ quarantine }} {{ item.dir }}"
    minute: "{{ item.minute | default('0') }}"
    hour: "{{ item.hour | default('*') }}"
    state: present
  with_items: "{{ cron_tabs }}"
  when: cron_tabs
