- name: Include global variables
  include_vars: variables/main.yml

- name: Update apt cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ __mysql_packages }}"

- name: Create databases
  become: true
  mysql_db:
    name: '{{ item.name }}'
    login_host: '{{ item.login_host|default("localhost") }}'
    login_user: '{{ item.login_user|default("") }}'
    login_password: '{{ item.login_password|default("") }}'
    login_port: '{{ item.login_port|default("3306") }}'
    login_unix_socket: '{{ item.login_unix_socket|default("") }}'
    collation: '{{ item.collation|default("utf8mb4_general_ci") }}'
    encoding: '{{ item.encoding|default("utf8mb4") }}'
    state: '{{ item.state|default("present") }}'
    target: '{{ item.target|default("") }}'
  with_items: '{{ mysql_databases }}'

- name: Create users
  become: true
  mysql_user:
    name: '{{ item.name }}'
    password: '{{ item.password }}'
    check_implicit_admin: true
    login_host: '{{ item.login_host|default("localhost") }}'
    login_user: '{{ item.login_user|default("") }}'
    login_password: '{{ item.login_password|default("") }}'
    login_port: '{{ item.login_port|default("3306") }}'
    login_unix_socket: '{{ item.login_unix_socket|default("") }}'
    encrypted: false
    state: present
    priv: '{{ item.priv }}'
    update_password: always
  with_items: '{{ mysql_users }}'

- name: Copy config
  become: true
  copy:
    src: files/my.cnf
    dest: /etc/mysql/conf.d/my.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mysql
