---
- name: Include global variables
  include_vars: variables/main.yml

- name: Update apt cache
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ __php7_packages }}"

- name: Replace fix_pathinfo
  become: true
  replace:
    regexp: '^;cgi\.fix_pathinfo=1$'
    replace: 'cgi.fix_pathinfo=0'
    path: '/etc/php/7.0/fpm/php.ini'
    backup: true
  notify: restart php7-fpm

- name: Install xdebug if in development
  become: true
  apt:
    name: php-xdebug
    state: present
  when: php7_development

- name: Add xdebug config
  become: true
  template:
    src: templates/xdebug.ini.j2
    dest: /etc/php/7.0/mods-available/xdebug.ini
    backup: true
    mode: 0644
    owner: root
    group: root
  when: php7_development

- name: Enable xdebug
  become: true
  command: phpenmod xdebug
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-xdebug.ini
  notify: restart php7-fpm
  when: php7_development

- name: Disable xdebug for cli
  become: true
  file:
    path: /etc/php/7.0/cli/conf.d/20-xdebug.ini
    state: absent

- name: Stat {{ php7_project_root }}
  stat:
    path: "{{ php7_project_root }}/composer.json"
  register: composer_file

- name: "Run composer if {{ php7_project_root }}/composer.json exists"
  command: composer install
  args:
    creates: "{{ php7_project_root }}/vendor"
    chdir: "{{ php7_project_root }}"
  when: composer_file.stat.exists
