- name: Include global variables
  include_vars: variables/main.yml

- name: Update apt cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ __modevasive_packages }}"

- name: Create modevasive log directory
  become: true
  file:
    path: "{{ modevasive_log_dir }}"
    state: directory
    owner: root
    group: www-data
    mode: 0330

- name: Create config
  become: true
  template:
    src: evasive.conf.j2
    dest: /etc/apache2/mods-available/evasive.conf
  notify: restart apache2

- name: Enable modevasive
  become: true
  command: a2enmod evasive
  notify: restart apache2
